repos:
# sort python imports
-   repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
    -   id: isort
# black formatting
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black-jupyter
        args: [--line-length=88,--preview]
# flake8 check
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ['--max-line-length=88','--extend-ignore=E203']
        exclude: ^data/archive/
# various checks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: detect-private-key
    -   id: check-added-large-files
        exclude_types: ["jupyter"] # because nb_stripout
    -   id: trailing-whitespace
