repos:
# trailing comma
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma
# f string for py files
-   repo: https://github.com/ikamensh/flynt/
    rev: '0.76'
    hooks:
    -   id: flynt
# sort python imports
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
# black formatting
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black-jupyter
        args: [--line-length=88,--preview]
# various checks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: detect-private-key
    -   id: check-added-large-files
        exclude_types: ["jupyter"] # because nb_stripout
    -   id: trailing-whitespace
# flake8 check
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: ['--max-line-length=88','--extend-ignore=E203']
        exclude: ^data/misc/
